version: '3.1'

services:

  postgresql:
    image: postgres
    restart: always
    volumes:
    - ./db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    env_file:
      - postgres.env
